name: VitalFix
version: @version@
main: com.tamrielnetwork.vitalfix.VitalFix
api-version: 1.17
authors: [ Tamriel Network ]
website: https://tamriel.site
description: Gives players the ability to fix their tools & armor.
commands:
  fix:
    description: "Main command"
    usage: "/fix"
permissions:
  vitalfix.fix:
    description: "Permission to fix tools & armor"
    default: op
  vitalfix.cooldown.bypass:
    description: "Permission to bypass cooldown"
    default: op